import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header'
import { SessionProvider } from "next-auth/react"

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  // pageProps: { session, ...pageProps },
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Header />
        {/* <SessionProvider session={session}> */}
          {children}
          {/* <Component {...pageProps} /> */}
      {/* </SessionProvider> */}
      </body>
    </html>
  );
}
